language: php

php:
  - '7.3'
  - '7.4'

branches:
  only:
    - master

before_script:
  - set -e
  - cp .env.travis .env
  - travis_retry composer install --no-interaction

script: composer run:coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
